### ISSUE TITLE
Example code for reading a local SBGN-ML file

### ISSUE THREAD

**Issue by bkutlu** [datapplab/SBGNview#1]
Hello, 
Is there an example code that I can look at for using SBGN-ML files from other sources? 
Thanks
-Burak

**Comment by wluo1** [comment]
Burak,
You can use custom SBGN-ML files in a similar way as using the default SBGN pathway collection. Just specify the path and filename using input.sbgn argument in SBGNview() function. For example and details check on these two sections of the SBGNview main tutorial:
https://bioconductor.org/packages/devel/bioc/vignettes/SBGNview/inst/doc/SBGNview.Vignette.html#75_Different_layouts_for_the_same_pathway

7.5 Different layouts for the same pathway
4.3.2 Custom SBGN-ML files
